scan_to_scan_filter_chain:
  ros__parameters:
    
    # Filter 1: Box Filter - Removes LiDAR beams hitting the robot body/wheels
    filter1:
      name: box_filter
      type: laser_filters/LaserScanBoxFilter
      params:
        box_frame: base_footprint
        invert: false
        min_x: -0.13
        max_x: 0.33
        min_y: -0.31
        max_y: 0.31
        min_z: -0.05
        max_z: 1.40

    # Filter 2: Range Filter - Limits LiDAR field of view
    filter2:
      name: range_filter
      type: laser_filters/LaserScanRangeFilter
      params:
        use_message_range_limits: false    # Ignore hardware limits (RPLIDAR S2E is 30m)
        lower_threshold: 0.06              # Lower limit: 6cm
        upper_threshold: 15.0              # Upper limit: 15m
        
        # CRITICAL: Handle out-of-bound beams
        lower_replacement_value: -.inf     # Beams < 6cm set to -inf (ignored)
        upper_replacement_value: .inf      # Beams > 15m set to +inf (Nav2 considers this free space, not obstacles)
        
    # Filter 3: Removes 60° → 70°
    filter3:
      name: remove_60_to_70
      type: laser_filters/LaserScanAngularBoundsFilterInPlace
      params:
        lower_angle:  1.68806   # 96.7°
        upper_angle:  1.88495   # 107.9°
        invert: false           # Clears beams IN this range

    # Filter 4: Removes 290° → 300° (= -70° → -60°)
    filter4:
      name: remove_290_to_300
      type: laser_filters/LaserScanAngularBoundsFilterInPlace
      params:
       lower_angle:  -1.93895 
       upper_angle:  -1.53806 
       invert: false            # Clears beams IN this range
       
    # Filter 5: Removes 291° → 300°
    filter5:
      name: remove_291_to_300
      type: laser_filters/LaserScanAngularBoundsFilterInPlace
      params:
       lower_angle:  -1.35895 
       upper_angle:  -0.37806 
       invert: false            # Clears beams IN this range
       
    # TF Synchronization Config
    tf_message_filter_target_frame: base_footprint
    tf_message_filter_queue_size: 20
    tf_message_filter_tolerance: 0.15